version: 2
jobs:
  build:
    docker:
      - image: trichards/password-generator
    steps:
      - checkout
      - run:
          name: Compile application
          command: make dist
      - run:
          name: Run unit tests
          command: make test
      - store_artifacts:
          path: password-generator
          destination: password-generator
